# Generated by Django 4.2.9 on 2026-03-05 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0001_initial'),
        ('links', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='link',
            name='customers',
            field=models.ManyToManyField(blank=True, related_name='links', to='customers.customer'),
        ),
    ]
